version: 0
title: Ideogram V3
thumbnail: https://huggingface.co/PiperMy/Pipelines/resolve/main/assets/logos/replicate_logo.svg
tags:
- text-to-image
- image-to-image
execution: regular
arrange:
  x: 1650
  y: 180
groups:
  inputs: {}
inputs:
  prompt:
    order: 2
    title: en=Prompt;ru=Промпт
    description: en=Text prompt for image generation;ru=Текстовая подсказка для генерации изображения
    type: string
    required: true
    featured: true
    multiline: true
    default: cat astronaut walking at a moon
  model:
    order: 1
    title: en=Model;ru=Модель
    description: en=Choose between Ideogram V3 models;ru=Выберите модель Ideogram V3
    type: string
    default: turbo
    enum:
    - turbo|en=Turbo;ru=Турбо
    - balanced|en=Balanced;ru=Сбалансированный
    - quality|en=Quality;ru=Качество
  aspect_ratio:
    order: 3
    title: en=Aspect Ratio;ru=Соотношение сторон
    description: en=Aspect ratio (ignored if resolution or inpainting image is set);ru=Соотношение сторон (игнорируется если задано разрешение или выбран режим inpainting)
    type: string
    default: 61
    enum:
    - 1:3|en=1:3;ru=1:3
    - 3:1|en=3:1;ru=3:1
    - 1:2|en=1:2;ru=1:2
    - 2:1|en=2:1;ru=2:1
    - 9:16|en=9:16;ru=9:16
    - 16:9|en=16:9;ru=16:9
    - 10:16|en=10:16;ru=10:16
    - 16:10|en=16:10;ru=16:10
    - 2:3|en=2:3;ru=2:3
    - 3:2|en=3:2;ru=3:2
    - 3:4|en=3:4;ru=3:4
    - 4:3|en=4:3;ru=4:3
    - 4:5|en=4:5;ru=4:5
    - 5:4|en=5:4;ru=5:4
    - 1:1|en=1:1;ru=1:1
  resolution:
    order: 4
    title: en=Resolution;ru=Разрешение
    description: en=Specific resolution (overrides aspect ratio, ignored for inpainting);ru=Определённое разрешение (заменяет соотношение сторон, игнорируется при inpainting)
    type: string
    default: None
    enum:
    - None|en=None;ru=Нет
    - 512x1536
    - 576x1408
    - 576x1472
    - 576x1536
    - 640x1344
    - 640x1408
    - 640x1472
    - 640x1536
    - 704x1152
    - 704x1216
    - 704x1280
    - 704x1344
    - 704x1408
    - 704x1472
    - 736x1312
    - 768x1088
    - 768x1216
    - 768x1280
    - 768x1344
    - 800x1280
    - 832x960
    - 832x1024
    - 832x1088
    - 832x1152
    - 832x1216
    - 832x1248
    - 864x1152
    - 896x960
    - 896x1024
    - 896x1088
    - 896x1120
    - 896x1152
    - 960x832
    - 960x896
    - 960x1024
    - 960x1088
    - 1024x832
    - 1024x896
    - 1024x960
    - 1024x1024
    - 1088x768
    - 1088x832
    - 1088x896
    - 1088x960
    - 1120x896
    - 1152x704
    - 1152x832
    - 1152x864
    - 1152x896
    - 1216x704
    - 1216x768
    - 1216x832
    - 1248x832
    - 1280x704
    - 1280x768
    - 1280x800
    - 1312x736
    - 1344x640
    - 1344x704
    - 1344x768
    - 1408x576
    - 1408x640
    - 1408x704
    - 1472x576
    - 1472x640
    - 1472x704
    - 1536x512
    - 1536x576
    - 1536x640
  style_type:
    order: 5
    title: en=Style Type;ru=Тип стиля
    description: en=Define the specific aesthetic of the image;ru=Укажите конкретный стиль изображения
    type: string
    default: None
    enum:
    - None|en=None;ru=Нет
    - Auto|en=Auto;ru=Авто
    - General|en=General;ru=Обычный
    - Realistic|en=Realistic;ru=Реалистичный
    - Design|en=Design;ru=Дизайн
  style_preset:
    order: 6
    title: en=Style Preset;ru=Стиль
    description: en=Apply a predefined artistic style (V3 models only);ru=Применить предопределённый стиль (только для V3)
    type: string
    default: None
    enum:
    - None|en=None;ru=Без стиля
    - 80s Illustration|en=80s Illustration;ru=Иллюстрация 80-х
    - 90s Nostalgia|en=90s Nostalgia;ru=Ностальгия 90-х
    - Abstract Organic|en=Abstract Organic;ru=Абстрактный органический
    - Analog Nostalgia|en=Analog Nostalgia;ru=Аналоговая ностальгия
    - Art Brut|en=Art Brut;ru=Брутальный арт
    - Art Deco|en=Art Deco;ru=Ар-деко
    - Art Poster|en=Art Poster;ru=Арт-постер
    - Aura|en=Aura;ru=Аура
    - Avant Garde|en=Avant Garde;ru=Авангард
    - Bauhaus|en=Bauhaus;ru=Bauhaus
    - Blueprint|en=Blueprint;ru=Чертёж
    - Blurry Motion|en=Blurry Motion;ru=Размытое движение
    - Bright Art|en=Bright Art;ru=Яркий арт
    - C4D Cartoon|en=C4D Cartoon;ru=C4D мультфильм
    - Children's Book|en=Children's Book;ru=Детская книга
    - Collage|en=Collage;ru=Коллаж
    - Coloring Book I|en=Coloring Book I;ru=Раскраска I
    - Coloring Book II|en=Coloring Book II;ru=Раскраска II
    - Cubism|en=Cubism;ru=Кубизм
    - Dark Aura|en=Dark Aura;ru=Тёмная аура
    - Doodle|en=Doodle;ru=Каляки
    - Double Exposure|en=Double Exposure;ru=Двойная экспозиция
    - Dramatic Cinema|en=Dramatic Cinema;ru=Драматичное кино
    - Editorial|en=Editorial;ru=Редакционный
    - Emotional Minimal|en=Emotional Minimal;ru=Эмоциональный минимализм
    - Ethereal Party|en=Ethereal Party;ru=Эфемерная вечеринка
    - Expired Film|en=Expired Film;ru=Просроченная пленка
    - Flat Art|en=Flat Art;ru=Плоский арт
    - Flat Vector|en=Flat Vector;ru=Векторная графика
    - Forest Reverie|en=Forest Reverie;ru=Лесное мечтание
    - Geo Minimalist|en=Geo Minimalist;ru=Гео-минимализм
    - Glass Prism|en=Glass Prism;ru=Стеклянная призма
    - Golden Hour|en=Golden Hour;ru=Золотой час
    - Graffiti I|en=Graffiti I;ru=Граффити I
    - Graffiti II|en=Graffiti II;ru=Граффити II
    - Halftone Print|en=Halftone Print;ru=Полутоно́вая печать
    - High Contrast|en=High Contrast;ru=Высокий контраст
    - Hippie Era|en=Hippie Era;ru=Эпоха хиппи
    - Iconic|en=Iconic;ru=Иконичный
    - Japandi Fusion|en=Japandi Fusion;ru=Джапанди фьюжн
    - Jazzy|en=Jazzy;ru=Джазовый
    - Long Exposure|en=Long Exposure;ru=Длинная выдержка
    - Magazine Editorial|en=Magazine Editorial;ru=Эдиториал журнала
    - Minimal Illustration|en=Minimal Illustration;ru=Минималистичная иллюстрация
    - Mixed Media|en=Mixed Media;ru=Смешанная техника
    - Monochrome|en=Monochrome;ru=Монохром
    - Nightlife|en=Nightlife;ru=Ночная жизнь
    - Oil Painting|en=Oil Painting;ru=Масляная живопись
    - Old Cartoons|en=Old Cartoons;ru=Старые мультфильмы
    - Paint Gesture|en=Paint Gesture;ru=Живописный жест
    - Pop Art|en=Pop Art;ru=Поп-арт
    - Retro Etching|en=Retro Etching;ru=Ретро-гравюра
    - Riviera Pop|en=Riviera Pop;ru=Ривьера-поп
    - Spotlight 80s|en=Spotlight 80s;ru=80-е в центре внимания
    - Stylized Red|en=Stylized Red;ru=Стилизованный красный
    - Surreal Collage|en=Surreal Collage;ru=Сюрреалистичный коллаж
    - Travel Poster|en=Travel Poster;ru=Постер путешествий
    - Vintage Geo|en=Vintage Geo;ru=Винтажная геометрия
    - Vintage Poster|en=Vintage Poster;ru=Винтажный постер
    - Watercolor|en=Watercolor;ru=Акварель
    - Weird|en=Weird;ru=Странный
    - Woodblock Print|en=Woodblock Print;ru=Ксилография
  seed:
    order: 7
    title: en=Seed;ru=Начальный шум
    description: en=Random seed for reproducible generation (leave empty for random);ru=Случайное число для воспроизводимости (оставьте пустым для случайного)
    type: integer
    min: 0
    max: 2147483647
    default: -1
  style_reference_images:
    order: 8
    title: en=Style Reference Images;ru=Референсы стиля
    description: en=Reference images for style (up to 5 images supported);ru=Изображения-референсы для стиля (до 5-ти изображений)
    type: image[]
outputs:
  image:
    title: en=Image;ru=Изображение
    type: image
    featured: true
catalog:
  _id: ideogram_v3_replicate
  version: 15
  category:
    _id: generate_images
    title: en=Generate Images;ru=Ген. изображений
    icon: image
    order: 5
  package: replicate
environment:
  REPLICATE_TOKEN:
    title: Replicate Token
    description: Go to [Replicate](https://replicate.com/account/api-tokens) to take a keys
    type: string
    scope: global
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@main/nodes/replicate/generate_images/ideogram_v3/script.js
