version: 1
title: Kling Video 2
description: Generate videos with Kling 2.1, 2.5, and 2.6 models
tags:
  - text-to-video
  - image-to-video
source: node
execution: regular
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@v2.0.4/nodes/fal/videos/kling_2/script.js
arrange:
  x: 690
  y: 500
groups:
  inputs: {}
inputs:
  prompt:
    order: 2
    title: en=Prompt;ru=Промпт
    description: en=Text prompt for video generation (max 2500 characters);ru=Текстовая подсказка для генерации видео (максимум 2500 символов)
    type: string
    required: true
    featured: true
    multiline: true
    default: cat astronaut walking at a moon
  image:
    order: 3
    title: en=Image;ru=Изображение
    description: en=Optional starting image;ru=Необязательное изображение для первого кадра видео
    type: image
    featured: true
  model:
    order: 1
    title: en=Version;ru=Версия
    description: |-
      en=2.1: Basic quality, I2V only (auto-switches to 2.5 for T2V)
      2.5: Better quality, faster
      2.6: Best quality with optional audio;ru=2.1: Базовое качество, только I2V (T2V автоматически переключает на 2.5)
      2.5: Лучшее качество, быстрее
      2.6: Наилучшее качество, опционально с аудио
    type: string
    default: 2_6
    enum:
      - 2_1|en=Kling 2.1;ru=Kling 2.1
      - 2_5|en=Kling 2.5;ru=Kling 2.5
      - 2_6|en=Kling 2.6;ru=Kling 2.6
  duration:
    order: 4
    title: en=Duration;ru=Длительность
    description: en=Video duration in seconds;ru=Длительность видео (секундах)
    type: string
    default: "5"
    enum:
      - 5|en=5 seconds;ru=5 секунд
      - 10|en=10 seconds;ru=10 секунд
  aspect_ratio:
    order: 5
    title: en=Aspect Ratio;ru=Соотношение сторон
    description: en=Video aspect ratio (only for T2V mode);ru=Соотношение сторон (только для режима T2V)
    type: string
    default: 16:9
    enum:
      - 16:9|en=16:9;ru=16:9
      - 9:16|en=9:16;ru=9:16
      - 1:1|en=1:1;ru=1:1
  negative_prompt:
    order: 7
    title: en=Negative Prompt;ru=Негативная подсказка
    description: en=What to avoid in the generated video;ru=Что не должно быть на сгенерированном видео
    type: string
    multiline: true
    default: blur, distort, and low quality
  cfg_scale:
    order: 8
    title: en=CFG Scale;ru=CFG шкала
    description: en=How closely to follow the prompt (0-1);ru=Насколько точно следовать подсказке (0-1)
    type: float
    min: 0
    max: 1
    step: 0.05
    default: 0.5
  generate_audio:
    order: 9
    title: en=Generate Audio;ru=Генерировать аудио
    description: en=Generate audio track (Kling 2.6 only, supports Chinese & English);ru=Генерировать аудио-дорожку (только Kling 2.6, поддержка китайский и английский)
    type: boolean
    default: true
  tail_image:
    order: 6
    title: en=Tail Image;ru=Финальный кадр
    description: en=Optional ending image for I2V interpolation (Kling 2.5 only);ru=Необязательное изображение для завершающего кадра (только Kling 2.5)
    type: image
outputs:
  video:
    title: en=Video;ru=Видео
    type: video
    featured: true
catalog:
  _id: kling_2_fal
  version: 10
  category:
    _id: generate_videos
    title: en=Generate videos;ru=Генерация видео
    icon: video
    order: 10
  package: fal
environment:
  FAL_KEY:
    title: Fal AI Key
    description: Go to [Fal AI](https://fal.ai/dashboard/keys) to get your API key
    type: string
    scope: global
