version: 1
icon: text
order: 5
title: en=Translate text;ru=Перевести текст
tags:
  - translate
  - en=cheap;ru=дешево
source: node
execution: regular
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@v2.0.4/nodes/artworks/translate_text/script.js
sign: acd11ce1b3cf4f3e51627f8a079f7600b6219c1af5e9d16cdbb5388c5039e06c
arrange:
  x: 440
  y: 100
groups:
  inputs: {}
inputs:
  source:
    order: 1
    title: en=Source language;ru=Исходный язык
    type: string
    default: auto
    enum:
      - auto|en=Auto;ru=Авто
      - en|en=English;ru=Английский
      - de|en=German;ru=Немецкий
      - ru|en=Russian;ru=Русский
      - es|en=Spanish;ru=Испанский
      - fr|en=French;ru=Французский
      - it|en=Italian;ru=Итальянский
      - pt|en=Portuguese;ru=Португальский
      - ja|en=Japanese;ru=Японский
      - ko|en=Korean;ru=Корейский
      - hi|en=Hindi;ru=Хинди
      - tr|en=Turkish;ru=Турецкий
      - zh|en=Chinese Simplified;ru=Китайский (упрощённый)
  target:
    order: 2
    title: en=Target;ru=Целевой язык
    type: string
    required: true
    default: en
    enum:
      - en|en=English;ru=Английский
      - de|en=German;ru=Немецкий
      - ru|en=Russian;ru=Русский
      - es|en=Spanish;ru=Испанский
      - fr|en=French;ru=Французский
      - it|en=Italian;ru=Итальянский
      - pt|en=Portuguese;ru=Португальский
      - ja|en=Japanese;ru=Японский
      - ko|en=Korean;ru=Корейский
      - hi|en=Hindi;ru=Хинди
      - tr|en=Turkish;ru=Турецкий
      - zh|en=Chinese Simplified;ru=Китайский (упрощённый)
  text:
    order: 3
    title: en=Text;ru=Текст
    type: string
    required: true
    featured: true
    multiline: true
outputs:
  text:
    title: en=Text;ru=Перевод
    type: string
    format: markdown
    featured: true
catalog:
  _id: translate_text_artworks
  version: 50
  category:
    _id: process_text
    title: en=Process text;ru=Обработка текста
    icon: text
    order: 35
  package: artworks
environment:
  ARTWORKS_USER:
    title: ArtWorks user
    description: Signup at https://artworks.ai/
    type: string
    scope: global
  ARTWORKS_PASSWORD:
    title: ArtWorks password
    type: string
    scope: global
