inputs:
  image:
    featured: true
    order: 1
    required: true
    title: en=Image;ru=Изображение
    type: image
outputs:
  scores:
    featured: true
    title: en=Scores;ru=Оценки
    type: json
