inputs:
  face:
    featured: true
    order: 1
    required: true
    title: en=Face;ru=Лицо
    type: image
  image:
    featured: true
    order: 2
    required: true
    title: en=Image;ru=Изображение
    type: image
outputs:
  image:
    featured: true
    title: en=Image;ru=Изображение
    type: image
