version: 1
order: 10
title: en=Face swap on image;ru=Замена лица на изображении
tags:
  - deep-swap
  - en=cheap;ru=дешево
source: node
execution: regular
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@v2.0.4/nodes/artworks/face_swap_on_image/script.js
arrange:
  x: 1030
  y: 910
groups:
  inputs: {}
inputs:
  face:
    order: 1
    title: en=Face;ru=Лицо
    type: image
    required: true
    featured: true
  image:
    order: 2
    title: en=Image;ru=Изображение
    type: image
    required: true
    featured: true
outputs:
  image:
    title: en=Image;ru=Изображение
    type: image
    featured: true
catalog:
  _id: face_swap_on_image_artworks
  version: 50
  category:
    _id: deep_swap
    title: en=Deep swap;ru=Глубокая замена
    icon: face
    order: 20
  package: artworks
environment:
  ARTWORKS_USER:
    title: ArtWorks user
    description: Signup at https://artworks.ai/
    type: string
    scope: global
  ARTWORKS_PASSWORD:
    title: ArtWorks password
    type: string
    scope: global
