version: 1
icon: face
order: 10
title: en=Detect face;ru=Определить лицо
tags:
  - object-detection
  - en=cheap;ru=дешево
source: node
execution: regular
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@v2.0.4/nodes/artworks/detect_face/script.js
arrange:
  x: 470
  y: 870
groups:
  inputs: {}
inputs:
  image:
    order: 1
    title: en=Image;ru=Изображение
    type: image
    required: true
    featured: true
  index:
    order: 2
    title: en=Index;ru=Индекс
    type: integer
    required: true
    default: 0
outputs:
  face:
    title: en=Face;ru=Лицо
    type: image
    featured: true
  features:
    title: en=Features;ru=Характеристики
    type: json
    schema: face-features
    featured: true
catalog:
  _id: detect_face_on_image_artworks
  version: 50
  category:
    _id: image_analysis
    title: en=Image analysis;ru=Анализ изображений
    icon: image
    order: 25
  package: artworks
environment:
  ARTWORKS_USER:
    title: ArtWorks user
    description: Signup at https://artworks.ai/
    type: string
    scope: global
  ARTWORKS_PASSWORD:
    title: ArtWorks password
    type: string
    scope: global
