version: 0
title: Google Imagen 4
thumbnail: https://huggingface.co/PiperMy/Pipelines/resolve/main/assets/logos/replicate_logo.svg
tags:
  - text-to-image
execution: regular
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@5b986ce8fd3f7edc99f19fe9d4e8b8091b11e753/nodes/replicate/generate_images/google_imagen4/script.js
arrange:
  x: 1940
  y: 700
groups:
  inputs: {}
inputs:
  prompt:
    order: 2
    title: en=Prompt;ru=Промпт
    description: en=Text prompt for image generation;ru=Текстовая подсказка для генерации изображения
    type: string
    required: true
    featured: true
    multiline: true
    default: cat astronaut walking at a moon
  model:
    order: 1
    title: en=Model;ru=Модель
    description: en=Choose between Imagen 4 models;ru=Выберите модель Imagen 4
    type: string
    default: imagen-4
    enum:
      - imagen-4-fast|en=Imagen 4 Fast;ru=Imagen 4 Fast
      - imagen-4|en=Imagen 4;ru=Imagen 4
      - imagen-4-ultra|en=Imagen 4 Ultra;ru=Imagen 4 Ultra
  aspect_ratio:
    order: 3
    title: en=Aspect Ratio;ru=Соотношение сторон
    description: en=Aspect ratio of the generated image;ru=Соотношение сторон генерируемого изображения
    type: string
    default: 61
    enum:
      - 1:1|en=1:1 (square);ru=1:1 (квадрат)
      - 9:16|en=9:16 (vertical);ru=9:16 (вертикальное)
      - 16:9|en=16:9 (wide);ru=16:9 (широкий)
      - 3:4|en=3:4 (portrait);ru=3:4 (портрет)
      - 4:3|en=4:3 (album);ru=4:3 (альбом)
  safety_filter_level:
    order: 4
    title: en=Safety Filter Level;ru=Уровень фильтра контента
    description: en=Content safety filter strictness;ru=Строгость фильтра безопасности
    type: string
    default: block_only_high
    enum:
      - block_low_and_above|en=Block low and above;ru=Блокировать низкий и выше
      - block_medium_and_above|en=Block medium and above;ru=Блокировать средний и выше
      - block_only_high|en=Block only high;ru=Блокировать только высокий
  output_format:
    order: 5
    title: en=Output Format;ru=Формат вывода
    description: en=Format of the output image;ru=Формат итогового изображения
    type: string
    default: jpg
    enum:
      - jpg|en=JPG;ru=JPG
      - png|en=PNG;ru=PNG
outputs:
  image:
    title: en=Image;ru=Изображение
    type: image
    featured: true
catalog:
  _id: google_imagen_4_replicate
  version: 15
  category:
    _id: generate_images
    title: en=Generate Images;ru=Ген. изображений
    icon: image
    order: 5
  package: replicate
environment:
  REPLICATE_TOKEN:
    title: Replicate Token
    description: Go to [Replicate](https://replicate.com/account/api-tokens) to take a keys
    type: string
    scope: global
