version: 1
icon: video
order: 5
title: en=WAN 2.x animate;ru=WAN 2.x анимация
tags:
  - image-to-video
  - en=cheap;ru=дешево
source: node
execution: regular
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@v2.0.3/nodes/artworks/wan_2_2/script.js
locked: false
arrange:
  x: 1640
  y: 2240
groups:
  inputs: {}
inputs:
  prompt:
    order: 3
    title: en=Prompt;ru=Подсказка
    type: string
    required: true
    featured: true
    multiline: true
    default: cat astronaut walking at a moon
  videoSize:
    order: 4
    title: en=Video size;ru=Размер видео
    type: string
    default: 512x512
    enum:
      - 512x512|en=512x512 (1:1) <Horizontal>;ru=512x512 (1:1) <Горизонтальное>
      - 960x960|en=960x960 (1:1) <Horizontal>;ru=960x960 (1:1) <Горизонтальное>
      - 720x720|en=720x720 (1:1) <Horizontal>;ru=720x720 (1:1) <Горизонтальное>
      - 832x480|en=832x480 (26:15) <Horizontal>;ru=832x480 (26:15) <Горизонтальное>
      - 832x624|en=832x624 (4:3) <Horizontal>;ru=832x624 (4:3) <Горизонтальное>
      - 960x544|en=960x544 (30:17) <Horizontal>;ru=960x544 (30:17) <Горизонтальное>
      - 1104x832|en=1104x832 (69:52) <Horizontal>;ru=1104x832 (69:52) <Горизонтальное>
      - 1280x544|en=1280x544 (40:17) <Horizontal>;ru=1280x544 (40:17) <Горизонтальное>
      - 1280x720|en=1280x720 (16:9) <Horizontal>;ru=1280x720 (16:9) <Горизонтальное>
      - 480x832|en=480x832 (15:26) <Vertical>;ru=480x832 (15:26) <Вертикальное>
      - 544x960|en=544x960 (17:30) <Vertical>;ru=544x960 (17:30) <Вертикальное>
      - 544x1280|en=544x1280 (17:40) <Vertical>;ru=544x1280 (17:40) <Вертикальное>
      - 624x832|en=624x832 (3:4) <Vertical>;ru=624x832 (3:4) <Вертикальное>
      - 720x1280|en=720x1280 (9:16) <Vertical>;ru=720x1280 (9:16) <Вертикальное>
      - 832x1104|en=832x1104 (52:69) <Vertical>;ru=832x1104 (52:69) <Вертикальное>
  image:
    order: 2
    title: en=Image;ru=Изображение
    type: image
    required: true
    featured: true
  resolution:
    order: 6
    title: en=Resolution;ru=Разрешение
    type: string
    default: 480p
    enum:
      - 480p
      - 720p
      - 1080p
  length:
    order: 5
    title: en=Length;ru=Длительность
    type: string
    default: 5s
    enum:
      - 5s|en=5s;ru=5 сек
      - 8s|en=8s;ru=8 сек
  fps:
    order: 7
    title: en=Fps;ru=Кадров в секунду
    type: string
    default: "16"
    enum:
      - 16|en=16;ru=16
      - 24|en=24;ru=24
      - 30|en=30;ru=30
      - 60|en=60;ru=60
  version:
    order: 1
    title: en=Version;ru=Версия
    type: string
    default: 2_2
    enum:
      - 2_1|Wan 2.1
      - 2_2|Wan 2.2
outputs:
  video:
    title: en=Video;ru=Видео
    type: video
    featured: true
catalog:
  _id: wan_2_2_animate
  version: 50
  category:
    _id: generate_videos
    title: en=Video generation;ru=Генерация видео
    icon: video
    order: 10
  package: artworks
environment:
  ARTWORKS_USER:
    title: ArtWorks user
    description: Signup at https://artworks.ai/
    type: string
    scope: global
  ARTWORKS_PASSWORD:
    title: ArtWorks password
    type: string
    scope: global
