version: 1
order: 5
title: en=Portrait studio;ru=Фото будка
tags:
  - deep-swap
  - en=cheap;ru=дешево
source: node
execution: regular
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@v2.0.4/nodes/artworks/pulid/script.js
arrange:
  x: 700
  y: 1370
groups:
  inputs: {}
inputs:
  person:
    order: 1
    title: en=Person;ru=Персона
    type: image
    required: true
    featured: true
  prompt:
    order: 2
    title: en=Prompt;ru=Подсказка
    type: string
    required: true
    featured: true
    multiline: true
    default: Close-up portrait of Harry Potter, detailed, high resolution
  upscale:
    order: 3
    title: en=Upscale;ru=Качество
    type: string
    default: no
    enum:
      - no|en=No enhancing;ru=Без улучшений
      - skin_detailing|en=Skin detailing;ru=Детализаци кожи
      - enhancing_quality|en=Enhancing quality;ru=Высокое разрешение
      - full_enhancing|en=Full enhancing;ru=Все улучшения
  aspectRatio:
    order: 4
    title: en=Aspect ratio;ru=Соотношение сторон
    type: string
    default: 9:16
    enum:
      - 1:1
      - 2:3
      - 3:4
      - 5:8
      - 9:16
      - 9:19
      - 9:21
      - 3:2
      - 4:3
      - 8:5
      - 16:9
      - 19:9
      - 21:9
outputs:
  image:
    title: Image
    type: image
    featured: true
catalog:
  _id: pulid_artworks
  version: 50
  category:
    _id: deep_swap
    title: en=Deep swap;ru=Глубокая замена
    icon: face
    order: 20
  package: artworks
environment:
  ARTWORKS_USER:
    title: ArtWorks user
    description: Signup at https://artworks.ai/
    type: string
    scope: global
  ARTWORKS_PASSWORD:
    title: ArtWorks password
    type: string
    scope: global
