version: 1
icon: text
order: 5
title: en=Ask LLM agent;ru=Спросить LLM
tags:
  - llm
  - multimodal
  - en=cheap;ru=дешево
source: node
execution: regular
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@e24efd0529f09811fb9d7c1570f5f995772f9836/nodes/artworks/ask_llm_agent/script.js
arrange:
  x: 240
  y: 1430
groups:
  inputs:
    main:
      order: 1
      title: en=Main Settings;ru=Основные настройки
    vision:
      order: 2
      title: en=Vision;ru=Изображение
    advanced:
      order: 3
      title: en=Advanced;ru=Дополнительно
inputs:
  model:
    order: 1
    title: en=Model;ru=Модель
    description: en=Select LLM model (Qwen3-VL supports images);ru=Выберите модель LLM (Qwen3-VL поддерживает изображения)
    group: main
    type: string
    featured: true
    default: deepseek-r1:8b
    enum:
      - deepseek-r1:8b|DeepSeek R1 8b
      - qwen3-vl:8b-instruct|Qwen3-VL 8b (Vision)
  answerFormat:
    order: 4
    title: en=Answer format;ru=Формат ответа
    description: en=Don't forget to add instructions for JSON format;ru=Не забудьте добавить инструкции для JSON формата
    group: advanced
    type: string
    required: true
    default: text
    enum:
      - text|Text
      - json|JSON
  question:
    order: 2
    title: en=Question;ru=Вопрос
    description: en=Your question or prompt;ru=Ваш вопрос или промпт
    group: main
    type: string
    required: true
    featured: true
    multiline: true
    default: What do you think about AI?
  instructions:
    order: 5
    title: en=System instructions;ru=Инструкции системе
    description: en=System prompt to guide the model's behavior;ru=Системный промпт для управления поведением модели
    group: advanced
    type: string
    multiline: true
  image:
    order: 3
    title: en=Image;ru=Изображение
    description: en=Optional image for Qwen3-VL model. Model works without it too.;ru=Опциональное изображение для Qwen3-VL. Модель работает и без него.
    group: vision
    type: image
outputs:
  text:
    title: en=Text;ru=Текст
    type: string
    format: markdown
    featured: true
  json:
    title: JSON
    type: json
    featured: true
catalog:
  _id: ask_llm_agent_artworks
  version: 50
  category:
    _id: llm_agents
    title: en=Language Agents;ru=Языковые агенты
    icon: agent
    order: 15
  package: artworks
environment:
  ARTWORKS_USER:
    title: ArtWorks user
    description: Signup at https://artworks.ai/ (not required for Qwen3-VL)
    type: string
    scope: global
  ARTWORKS_PASSWORD:
    title: ArtWorks password
    description: Not required for Qwen3-VL
    type: string
    scope: global
