version: 1
icon: video
order: 5
title: en=Extract frame;ru=Извлечь кадр
tags:
  - edit-video
  - en=cheap;ru=дешево
source: node
execution: regular
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@e24efd0529f09811fb9d7c1570f5f995772f9836/nodes/artworks/extract_frame/script.js
arrange:
  x: 2560
  y: 2080
groups:
  inputs: {}
inputs:
  video:
    order: 1
    title: en=Video;ru=Видео
    type: video
    required: true
    featured: true
  position:
    order: 2
    title: en=Position;ru=Позиция
    type: string
    default: last
    enum:
      - first|en=First frame;ru=Первый кадр
      - last|en=Last frame;ru=Последний кадр
outputs:
  frame:
    title: en=Frame;ru=Фрейм
    type: image
    featured: true
catalog:
  _id: extract_frame_artworks
  version: 50
  category:
    _id: video_processing
    title: en=Video processing;ru=Обработка видео
    icon: video
    order: 30
  package: artworks
environment:
  ARTWORKS_USER:
    title: ArtWorks user
    description: Signup at https://artworks.ai/
    type: string
    scope: global
  ARTWORKS_PASSWORD:
    title: ArtWorks password
    type: string
    scope: global
