version: 1
title: en=Upscale image;ru=Увеличить изображение
tags:
  - upscale
  - en=cheap;ru=дешево
source: node
execution: regular
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@v2.0.3/nodes/artworks/upscale_image/script.js
arrange:
  x: 2030
  y: 140
groups:
  inputs: {}
inputs:
  image:
    order: 1
    title: en=Image;ru=Изображение
    type: image
    required: true
    featured: true
  upscalingResize:
    order: 2
    title: en=Resize;ru=Увеличение
    type: float
    required: true
    min: 0.1
    max: 4
    step: 0.1
    default: 2
outputs:
  image:
    title: en=Image;ru=Изображение
    type: image
    featured: true
catalog:
  _id: upscale_image_artworks
  version: 50
  category:
    _id: generate_images
    title: en=Generate images;ru=Ген. изображений
  package: artworks
environment:
  ARTWORKS_USER:
    title: ArtWorks user
    description: Signup at https://artworks.ai/
    type: string
    scope: global
  ARTWORKS_PASSWORD:
    title: ArtWorks password
    type: string
    scope: global
