version: 1
title: Minimax Hailuo 2.3
description: Generate videos with Minimax Hailuo 2.3 models (Standard, Fast, Pro, Pro Fast)
tags:
  - text-to-video
  - image-to-video
source: node
execution: regular
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@v2.0.3/nodes/fal/videos/hailuo_2_3/script.js
arrange:
  x: 1490
  y: 590
groups:
  inputs: {}
inputs:
  prompt:
    order: 2
    title: en=Prompt;ru=Промпт
    description: en=Text prompt for video generation (max 2000 characters);ru=Текстовая подсказка для генерации видео (макс. 2000 символов)
    type: string
    required: true
    featured: true
    multiline: true
    default: cat astronaut walking at a moon
  image:
    order: 3
    title: en=Image;ru=Изображение
    description: en=Optional starting image;ru=Опциональное начальное изображение
    type: image
    featured: true
  model:
    order: 1
    title: en=Model Version;ru=Версия модели
    description: |-
      en=2.3: Standard quality;ru=2.3: стандартное качество
      en=2.3-fast: Faster, I2V only (auto-switches to 2.3 for T2V);ru=2.3-fast: быстрее, только I2V (T2V автоматически выбирает 2.3)
      en=2.3-pro: Best quality;ru=2.3-pro: лучшее качество
      en=2.3-pro-fast: Fast Pro, I2V only (auto-switches to 2.3-pro for T2V);ru=2.3-pro-fast: быстрый Pro, только I2V (T2V автоматически выбирает 2.3-pro)
    type: string
    default: 2_3
    enum:
      - 2_3|en=Hailuo 2.3;ru=Hailuo 2.3
      - 2_3_fast|en=Hailuo 2.3 Fast;ru=Hailuo 2.3 Быстрый
      - 2_3_pro|en=Hailuo 2.3 Pro;ru=Hailuo 2.3 Про
      - 2_3_pro_fast|en=Hailuo 2.3 Pro Fast;ru=Hailuo 2.3 Про Быстрый
  duration:
    order: 4
    title: en=Duration;ru=Длительность
    description: en=Video duration (Pro models auto-switch to 6s);ru=Длительность видео (Pro модели автоматически выбирают 6 секунд)
    type: string
    default: 6
    enum:
      - 6|en=6 seconds;ru=6 секунд
      - 10|en=10 seconds;ru=10 секунд
  prompt_optimizer:
    order: 5
    title: en=Prompt Optimizer;ru=Оптимизатор промпта
    description: en=Use model's built-in prompt enhancement;ru=Использовать встроенное улучшение промпта
    type: boolean
    default: true
outputs:
  video:
    title: en=Video;ru=Видео
    type: video
    featured: true
catalog:
  _id: hailuo_2_fal
  version: 10
  category:
    _id: generate_videos
    title: en=Generate videos;ru=Генерация видео
    icon: video
    order: 10
  package: fal
environment:
  FAL_KEY:
    title: Fal AI Key
    description: Go to [Fal AI](https://fal.ai/dashboard/keys) to get your API key
    type: string
    scope: global
