version: 1
icon: video
order: 10
title: en=Merge videos;ru=Объединить видео
tags:
  - edit-video
  - en=cheap;ru=дешево
source: node
execution: regular
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@v2.0.4/nodes/artworks/merge_videos/script.js
arrange:
  x: 2130
  y: 2080
groups:
  inputs: {}
inputs:
  video1:
    order: 3
    title: en=Video 1;ru=Видео 1
    type: video
    required: true
    featured: true
    dynamic:
      group: videos
      id: video#
      title: "en=Video #;ru=Видео #"
      index: 1
  video2:
    order: 4
    title: en=Video 2;ru=Видео 2
    type: video
    required: true
    featured: true
    dynamic:
      group: videos
      id: video#
      title: "en=Video #;ru=Видео #"
      index: 2
    cloned: true
  width:
    order: 1
    title: en=Width;ru=Ширина
    type: integer
    required: true
    default: "1024"
  height:
    order: 2
    title: en=Height;ru=Высота
    type: integer
    required: true
    default: 768
outputs:
  video:
    title: en=Video;ru=Видео
    type: video
    featured: true
catalog:
  _id: merge_videos_artworks
  version: 50
  category:
    _id: video_processing
    title: en=Video processing;ru=Обработка видео
    icon: video
    order: 30
  package: artworks
environment:
  ARTWORKS_USER:
    title: ArtWorks user
    description: Signup at https://artworks.ai/
    type: string
    scope: global
  ARTWORKS_PASSWORD:
    title: ArtWorks password
    type: string
    scope: global
