version: 1
title: en=Image to image;ru=Пересоздать изображение
tags:
  - image-to-image
  - en=cheap;ru=дешево
execution: regular
script: https://cdn.jsdelivr.net/gh/my-piper/piper-nodes@e24efd0529f09811fb9d7c1570f5f995772f9836/nodes/artworks/image_to_image/script.js
arrange:
  x: 1530
  y: 140
groups:
  inputs:
    base:
      order: 1
      title: en=Base;ru=Базовые параметры
    SDXL:
      order: 2
      title: SDXL
      description: Only for SDXL checkpoints
inputs:
  image:
    order: 1
    title: en=Image;ru=Изображение
    group: base
    type: image
    required: true
    featured: true
  prompt:
    order: 2
    title: en=Prompt;ru=Подсказка
    group: base
    type: string
    required: true
    featured: true
    multiline: true
    default: cat walking on the Mars
  negativePrompt:
    order: 4
    title: en=Negative prompt;ru=Негативная подсказка
    group: base
    type: string
    multiline: true
  checkpoint:
    order: 3
    title: en=Checkpoint;ru=Модель
    group: base
    type: string
    required: true
    default: juggernautXL_v9Rundiffusionphoto2.safetensors
    enum:
      - juggernautXL_v9Rundiffusionphoto2.safetensors|Juggernaut XL <SDXL>
      - STOIQONewrealityFLUXSD_F1DPreAlpha.safetensors|New Reality Flux <Flux>
      - dynavisionXLAllInOneStylized_releaseV0610Bakedvae.safetensors|DynaVision XL All In One <SDXL>
      - flux1DevHyperNF4Flux1DevBNB_flux1DevHyperNF4.safetensors|Hyper NF4 Flux 1 <Flux>
      - aamXLAnimeMix_v10.safetensors|AAM XL (Anime Mix) <SDXL> <Fantasy>
      - raemuXL_v40.safetensors|Raemu XL <SDXL>
      - animaPencilXL_v260.safetensors|Anima Pencil XL <SDXL> <Fantasy>
      - leosamsHelloworldXL_helloworldXL50GPT4V.safetensors|Helloworld XL <SDXL>
      - albedobaseXL_v20.safetensors|AlbedoBase XL <SDXL>
      - afroditexlNudePeople_20Bkdvae.safetensors|Nude People <NSFW>
      - nosft-float8-e4m3fn.safetensors|Flux Nude People <NSFW>
      - asdf_0.4a_lorapov_0.2_lust_0.4.fp16.safetensors|Real Porn <NSFW>
      - PonyASDF_0.4_f6cosineb.fp16.safetensors|Real Porn Pony <NSFW>
      - Sexy_Aesthetic_SDXL_0.4x0.2.fp16.safetensors|Sexy & Beauty <NSFW>
      - aniku_0.2.fp16.safetensors|Anime Desire <NSFW>
      - anikurender_0.4b.fp16.safetensors|Hardcore Fantasy <NSFW>
  denoisingStrength:
    order: 6
    title: en=Denoising strength;ru=Степень изменения
    group: base
    type: float
    min: 0.1
    max: 1
    step: 0.05
    default: 0.5
  cfgScale:
    order: 7
    title: en=CFG scale;ru=Креативность
    group: base
    type: integer
    min: 1
    max: 20
    step: 1
    default: 7
  imageSize:
    order: 5
    title: en=Image size;ru=Размер изображения
    group: base
    type: string
    placeholder: auto:auto
    default: auto:auto
    enum:
      - auto:1024|en=auto:1024;ru=авто:1024
      - 1024:auto|en=1024:auto;ru=1024:авто
      - auto:auto|en=auto:auto;ru=авто:авто
  performance:
    order: 8
    title: en=Performance;ru=Производительность
    group: base
    type: string
    default: speed
    enum:
      - express|en=⚡ Express;ru=⚡ Экспресс
      - speed|en=🚅 Speed;ru=🚅 Скорость
      - quality|en=💎 Quality;ru=💎 Качество
  seed:
    order: 10
    title: en=Seed;ru=Начальный шум
    group: base
    type: integer
    placeholder: "-1"
  batchSize:
    order: 9
    title: en=Batch size;ru=Кол-во
    group: base
    type: integer
    min: 1
    max: 4
    step: 1
    default: 1
  sharpness:
    order: 1
    title: en=Sharpness;ru=Фотоэффект
    group: SDXL
    type: integer
    min: 0
    max: 30
    step: 1
    default: 2
outputs:
  images:
    title: en=Images;ru=Изображения
    type: image[]
    featured: true
catalog:
  _id: image_to_image_artworks
  version: 50
  category:
    _id: generate_images
    title: en=Generate images;ru=Ген. изображений
  package: artworks
environment:
  ARTWORKS_USER:
    title: ArtWorks user
    description: Signup at https://artworks.ai/
    type: string
    scope: global
  ARTWORKS_PASSWORD:
    title: ArtWorks password
    type: string
    scope: global
